"""agregar fecha_nacimiento a persona

Revision ID: 69456cdc466e
Revises: 
Create Date: 2026-04-08 08:12:28.066296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69456cdc466e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.Enum('Femenino', 'Masculino', 'Otro', 'Sin especificar'), nullable=True))
        batch_op.add_column(sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True))

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('stock_actual',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('stock_actual',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_column('ultima_actualizacion')
        batch_op.drop_column('genero')
        batch_op.drop_column('fecha_nacimiento')

    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
