"""Descripción del cambio

Revision ID: 999c6293ded4
Revises: dff30260b84e
Create Date: 2026-04-16 04:46:21.365468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '999c6293ded4'
down_revision = 'dff30260b84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('fecha_hora',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('estatus',
               existing_type=mysql.ENUM('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'FINALIZADA'),
               nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))
        batch_op.alter_column('id_cliente',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_empleado',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('detalle_cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_uñas', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('codigo_producto_color', sa.String(length=50), nullable=True))
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('descuento',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.create_foreign_key(None, 'producto', ['codigo_producto_color'], ['codigo_producto'])

    with op.batch_alter_table('insumo_servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_color', sa.Boolean(), nullable=False))
        batch_op.alter_column('id_servicio',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('codigo_producto',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cantidad_utilizada',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumo_servicio', schema=None) as batch_op:
        batch_op.alter_column('cantidad_utilizada',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('codigo_producto',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id_servicio',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('es_color')

    with op.batch_alter_table('detalle_cita', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('descuento',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.drop_column('codigo_producto_color')
        batch_op.drop_column('color_uñas')

    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('id_empleado',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_cliente',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('estatus',
               existing_type=mysql.ENUM('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'FINALIZADA'),
               nullable=True,
               existing_server_default=sa.text("'PENDIENTE'"))
        batch_op.alter_column('fecha_hora',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
