"""cambios de oscar

Revision ID: dff30260b84e
Revises: 
Create Date: 2026-04-13 00:05:23.866996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dff30260b84e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_promocion', sa.Integer(), nullable=True))
        batch_op.alter_column('id_cita',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'promocion', ['id_promocion'], ['id_promocion'])

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('foto')

    with op.batch_alter_table('detalle_cita', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_cita',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('id_promocion')

    # ### end Alembic commands ###
